print ("My daily routine")
print ("I wake up at 6:30")
print ("I leave the house at 7:30 and walk to school")
print ("I study at school for 6 hours and 35 minutes")
print ("I leave school at 2:45 or 3:35")
print ("I go home and sometimes play cricket after school")
print ("I then do my homework for 1 hour")
print ("I go to bed at 22:00")
print ("Weekly hours studied in a week:", 1 * 7)